name: Angular Tests

on: [push]

jobs:
  ng-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Install dependencies (npm ci)
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_INSTALL_BINARY: 0
    - name: Test (npm run test)
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  ng-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Install dependencies (npm ci)
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_INSTALL_BINARY: 0
    - name: Lint (npm run lint)
      run: npm run lint

  ng-build-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Install dependencies (npm ci)
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_INSTALL_BINARY: 0
    - name: Build (npm run build)
      run: npm run build -- --prod
