name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache firebase emulators
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        record: true
        start: npm run firebase:emulator
        command: npm run e2e -- --record
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
