name: Firebase Tests

on: [push]

jobs:
  firestore-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache firebase emulators
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Install dependencies (npm ci)
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_INSTALL_BINARY: 0
    - name: Test (npm run test-firestore)
      run: npm run test-firestore
